In [11]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np

from dlib_models import download_model, download_predictor, load_dlib_models
download_model()
download_predictor()
from dlib_models import models

load_dlib_models()
face_detect = models["face detect"]
face_rec_model = models["face rec"]
shape_predictor = models["shape predict"]

File already exists:
	/Users/christinaxiao/Christina/COLLEGE/Camps/MIT Beaver/Class/Week 2 - Visual/DlibModels/dlib_models/dlib_face_recognition_resnet_model_v1.dat
File already exists:
	/Users/christinaxiao/Christina/COLLEGE/Camps/MIT Beaver/Class/Week 2 - Visual/DlibModels/dlib_models/shape_predictor_68_face_landmarks.dat


In [77]:
import skimage.io as io 

def image_file_to_image_array(path):
    """ Given an image file, load the file as an image array.
    
        Parameters
        ----------
        path : string
            describes the path of the image
                        
        Returns
        -------
        The image file as an image array. """
    
    return io.imread(path)

In [81]:
x = image_file_to_image_array('./../me2.jpg')
print(x)

[[[210 210 210]
  [211 211 211]
  [210 210 210]
  ...
  [217 209 198]
  [219 211 200]
  [222 214 203]]

 [[210 210 210]
  [210 210 210]
  [210 210 210]
  ...
  [218 210 199]
  [220 212 201]
  [221 213 202]]

 [[210 210 210]
  [210 210 210]
  [210 210 210]
  ...
  [218 210 199]
  [219 211 200]
  [220 212 201]]

 ...

 [[ 49  48  56]
  [ 48  47  55]
  [ 47  46  54]
  ...
  [208 199 190]
  [206 197 188]
  [205 196 187]]

 [[ 48  47  55]
  [ 48  47  55]
  [ 48  47  55]
  ...
  [208 199 190]
  [208 199 190]
  [209 200 191]]

 [[ 46  45  53]
  [ 47  46  54]
  [ 48  47  55]
  ...
  [206 197 188]
  [207 198 189]
  [208 199 190]]]


In [84]:
def load_image_to_descriptors(image, name):
    """ Given an image array with 1 known face, return the description
    vector of that face. 
    
        Parameters
        ----------
        image : numpy.ndarray, shape = (N, M)
            2D array of shape (N, M)
            
        name : string
            
        Returns
        -------
        A tuple containing the name and the descriptor of the face. """
    
    detections = list(face_detect(image))
    assert len(detections) == 1 
    
    shape = shape_predictor(image, detections[0])
    descriptor = np.array(face_rec_model.compute_face_descriptor(image, shape))
    return (name, descriptor)

In [85]:
print(load_image_to_descriptors(x, "Christina"))

('Christina', array([-0.0786432 ,  0.04294607,  0.07657269, -0.07076743, -0.09497701,
        0.0004479 , -0.05484635, -0.07795386,  0.16304944, -0.19538249,
        0.26212364, -0.06680102, -0.19727291, -0.07386839, -0.0331938 ,
        0.1885909 , -0.1229227 , -0.14431182, -0.06493843, -0.00778329,
        0.11034247, -0.0201125 , -0.01116149,  0.03229155, -0.11611427,
       -0.33766016, -0.12753594, -0.01676958,  0.00913954, -0.10018289,
       -0.07695435,  0.04002907, -0.19409822, -0.02854539, -0.00567736,
        0.10893493, -0.01374299, -0.11828098,  0.14699878,  0.00490975,
       -0.24799332,  0.03506482,  0.00174546,  0.18029684,  0.11348797,
        0.00361929,  0.04190337, -0.1792856 ,  0.10304795, -0.13006869,
        0.03754717,  0.17692125,  0.0820487 ,  0.05505865,  0.01598391,
       -0.11862371,  0.02186619,  0.13621557, -0.0833837 , -0.01050348,
        0.03794326, -0.0160571 , -0.00957321, -0.12555288,  0.17007963,
        0.09597096, -0.10436939, -0.20008999,  0.1

In [83]:
from camera import take_picture

pic = take_picture()

load_image_to_descriptors(pic, "Christina")

('Christina',
 array([-0.07550356,  0.03789659,  0.06937249, -0.06860241, -0.09680024,
         0.02291182, -0.05036481, -0.07496497,  0.16341287, -0.19371437,
         0.27663434, -0.07084808, -0.21292789, -0.09403943, -0.03880099,
         0.20438533, -0.14868782, -0.14956357, -0.02276217,  0.01472224,
         0.09472391, -0.03041653, -0.00567719,  0.04507521, -0.10034709,
        -0.37659463, -0.14861284, -0.02799086, -0.02866128, -0.08452046,
        -0.08403769,  0.05401313, -0.20288712, -0.02991082,  0.00279986,
         0.09641737, -0.0268979 , -0.10803565,  0.13141684,  0.00641982,
        -0.21250524,  0.02245482,  0.01807993,  0.19714978,  0.09815748,
         0.04132213,  0.03589741, -0.13389722,  0.07843122, -0.14904878,
         0.05149099,  0.16684058,  0.07105721,  0.05653474,  0.00815662,
        -0.13387066,  0.02039982,  0.13178642, -0.08679041,  0.0049322 ,
         0.03727531, -0.05096401, -0.0145987 , -0.13813113,  0.1949611 ,
         0.11238541, -0.10667383, -0.

In [95]:
def match_image_to_descriptors(image):
    """ Given an image array with some amount of unknown faces, returns the 
    description vectors of each face present in the image.
        
        Parameters
        ----------
        image : numpy.ndarray, shape = (N, M)
            2D array of shape (N, M)
            
        Returns
        -------
        An array of the descriptors of all faces present in the image array. """
    
    detections = list(face_detect(image))
    out = []
    
    for face in range(len(detections)):
        shape = shape_predictor(image, detections[face])
        descriptor = np.array(face_rec_model.compute_face_descriptor(image, shape))
        out.append(descriptor)
        
    return np.array(out)

In [96]:
from camera import take_picture

pic = take_picture()

match_image_to_descriptors(pic)

array([[-6.32738620e-02,  4.93272729e-02,  8.50924551e-02,
        -5.04543036e-02, -1.08348198e-01,  3.26704159e-02,
        -7.20392168e-02, -7.02154785e-02,  1.62531003e-01,
        -1.86828032e-01,  2.41368949e-01, -5.08718304e-02,
        -1.71689093e-01, -6.41462728e-02, -5.18613942e-02,
         1.82912976e-01, -1.09632269e-01, -1.31668687e-01,
        -3.02194599e-02, -6.63705927e-04,  1.23530939e-01,
        -1.50091769e-02, -2.87682042e-02,  5.84321003e-03,
        -1.10268734e-01, -3.54282379e-01, -1.36393324e-01,
        -2.97430698e-02, -1.26815047e-02, -9.81815308e-02,
        -6.80639967e-02,  4.66534607e-02, -1.65088952e-01,
        -2.39112638e-02,  1.93627329e-05,  1.10717960e-01,
        -5.00381272e-03, -1.25020340e-01,  1.19614892e-01,
         1.65564045e-02, -2.41479918e-01,  3.60335559e-02,
        -4.54387348e-03,  1.86759755e-01,  8.41997117e-02,
         1.82109177e-02,  5.79350553e-02, -1.50968984e-01,
         1.08465165e-01, -1.36489943e-01,  4.55230512e-0