In [11]:
%matplotlib notebook
import matplotlib.pyplot as plt
import numpy as np

from dlib_models import download_model, download_predictor, load_dlib_models
download_model()
download_predictor()
from dlib_models import models

load_dlib_models()
face_detect = models["face detect"]
face_rec_model = models["face rec"]
shape_predictor = models["shape predict"]

File already exists:
	/Users/christinaxiao/Christina/COLLEGE/Camps/MIT Beaver/Class/Week 2 - Visual/DlibModels/dlib_models/dlib_face_recognition_resnet_model_v1.dat
File already exists:
	/Users/christinaxiao/Christina/COLLEGE/Camps/MIT Beaver/Class/Week 2 - Visual/DlibModels/dlib_models/shape_predictor_68_face_landmarks.dat


In [97]:
from camera import take_picture

def camera_to_image_array():
    """ Takes a picture and loads it as an image array.
                            
        Returns
        -------
        The picture as an image array. """    
    
    return take_picture()

In [77]:
import skimage.io as io 

def image_file_to_image_array(path):
    """ Given an image file, load the file as an image array.
    
        Parameters
        ----------
        path : string
            describes the path of the image
                        
        Returns
        -------
        The image file as an image array. """
    
    return io.imread(path)

In [98]:
y = camera_to_image_array()
print(y)

[[[ 59  48  18]
  [ 55  44  15]
  [ 56  42  18]
  ...
  [ 84  70  78]
  [ 74  57  70]
  [ 72  55  68]]

 [[ 63  52  23]
  [ 63  52  23]
  [ 58  44  20]
  ...
  [ 84  70  78]
  [ 82  65  78]
  [ 75  58  71]]

 [[ 79  60  44]
  [ 78  59  43]
  [ 68  46  35]
  ...
  [ 88  69  78]
  [ 85  68  81]
  [ 84  66  79]]

 ...

 [[ 12   2  11]
  [ 12   2  11]
  [ 11   1   8]
  ...
  [ 58 110 162]
  [ 68 121 170]
  [ 73 125 175]]

 [[ 12   0  14]
  [ 14   1  15]
  [ 13   3  12]
  ...
  [ 61 109 164]
  [ 68 117 172]
  [ 78 128 182]]

 [[ 14   1  15]
  [ 15   2  16]
  [ 13   3  12]
  ...
  [ 53 100 156]
  [ 66 116 171]
  [ 71 121 175]]]


In [81]:
x = image_file_to_image_array('./../me2.jpg')
print(x)

[[[210 210 210]
  [211 211 211]
  [210 210 210]
  ...
  [217 209 198]
  [219 211 200]
  [222 214 203]]

 [[210 210 210]
  [210 210 210]
  [210 210 210]
  ...
  [218 210 199]
  [220 212 201]
  [221 213 202]]

 [[210 210 210]
  [210 210 210]
  [210 210 210]
  ...
  [218 210 199]
  [219 211 200]
  [220 212 201]]

 ...

 [[ 49  48  56]
  [ 48  47  55]
  [ 47  46  54]
  ...
  [208 199 190]
  [206 197 188]
  [205 196 187]]

 [[ 48  47  55]
  [ 48  47  55]
  [ 48  47  55]
  ...
  [208 199 190]
  [208 199 190]
  [209 200 191]]

 [[ 46  45  53]
  [ 47  46  54]
  [ 48  47  55]
  ...
  [206 197 188]
  [207 198 189]
  [208 199 190]]]


In [84]:
def load_image_to_descriptors(image, name):
    """ Given an image array with 1 known face, return the description
    vector of that face. 
    
        Parameters
        ----------
        image : numpy.ndarray, shape = (N, M)
            2D array of shape (N, M)
            
        name : string
            
        Returns
        -------
        A tuple containing the name and the descriptor of the face. """
    
    detections = list(face_detect(image))
    assert len(detections) == 1 
    
    shape = shape_predictor(image, detections[0])
    descriptor = np.array(face_rec_model.compute_face_descriptor(image, shape))
    return (name, descriptor)

In [85]:
print(load_image_to_descriptors(x, "Christina"))

('Christina', array([-0.0786432 ,  0.04294607,  0.07657269, -0.07076743, -0.09497701,
        0.0004479 , -0.05484635, -0.07795386,  0.16304944, -0.19538249,
        0.26212364, -0.06680102, -0.19727291, -0.07386839, -0.0331938 ,
        0.1885909 , -0.1229227 , -0.14431182, -0.06493843, -0.00778329,
        0.11034247, -0.0201125 , -0.01116149,  0.03229155, -0.11611427,
       -0.33766016, -0.12753594, -0.01676958,  0.00913954, -0.10018289,
       -0.07695435,  0.04002907, -0.19409822, -0.02854539, -0.00567736,
        0.10893493, -0.01374299, -0.11828098,  0.14699878,  0.00490975,
       -0.24799332,  0.03506482,  0.00174546,  0.18029684,  0.11348797,
        0.00361929,  0.04190337, -0.1792856 ,  0.10304795, -0.13006869,
        0.03754717,  0.17692125,  0.0820487 ,  0.05505865,  0.01598391,
       -0.11862371,  0.02186619,  0.13621557, -0.0833837 , -0.01050348,
        0.03794326, -0.0160571 , -0.00957321, -0.12555288,  0.17007963,
        0.09597096, -0.10436939, -0.20008999,  0.1

In [99]:
load_image_to_descriptors(y, "Christina")

('Christina',
 array([-6.43596724e-02,  1.72377322e-02,  5.90304695e-02, -7.30975196e-02,
        -1.12965286e-01,  3.03101391e-02, -5.29604070e-02, -5.05873300e-02,
         1.74770311e-01, -2.15560749e-01,  2.92981505e-01, -1.09038793e-01,
        -2.18041062e-01, -2.15089712e-02, -5.49996942e-02,  2.07449287e-01,
        -1.76514283e-01, -1.19224645e-01, -8.90323613e-03,  1.19440339e-03,
         1.21435732e-01, -1.15065994e-02, -1.33834844e-02,  4.22199741e-02,
        -1.38545334e-01, -3.67536515e-01, -6.99789301e-02, -3.32302824e-02,
         4.95885648e-02, -4.74914275e-02, -6.87649772e-02,  9.12697390e-02,
        -2.01556116e-01, -8.47184937e-03, -8.50369129e-03,  1.01224303e-01,
        -1.15004750e-02, -6.93626702e-02,  1.59982830e-01,  1.74695570e-02,
        -2.62718946e-01,  2.63809925e-04,  1.00191161e-02,  2.03304380e-01,
         9.62605327e-02,  5.19750454e-02,  4.11229879e-02, -1.56686753e-01,
         7.11912587e-02, -1.68952063e-01,  7.61856884e-02,  1.22105919e-01

In [95]:
def match_image_to_descriptors(image):
    """ Given an image array with some amount of unknown faces, returns the 
    description vectors of each face present in the image.
        
        Parameters
        ----------
        image : numpy.ndarray, shape = (N, M)
            2D array of shape (N, M)
            
        Returns
        -------
        An array of the descriptors of all faces present in the image array. """
    
    detections = list(face_detect(image))
    out = []
    
    for face in range(len(detections)):
        shape = shape_predictor(image, detections[face])
        descriptor = np.array(face_rec_model.compute_face_descriptor(image, shape))
        out.append(descriptor)
        
    return np.array(out)

In [101]:
from camera import take_picture

pic = take_picture()

match_image_to_descriptors(pic)

array([[-0.07845727, -0.01495571,  0.07062414, -0.05228626, -0.07357599,
         0.05785215,  0.01048291, -0.08669036,  0.15925267, -0.21723711,
         0.27477881, -0.11714787, -0.20410289, -0.06285311, -0.05034479,
         0.1795312 , -0.11781647, -0.15034832, -0.0302467 , -0.00521027,
         0.05730314, -0.07481109, -0.01264951,  0.04985667, -0.13935843,
        -0.35993314, -0.15768051, -0.08301569,  0.01027092, -0.05343146,
        -0.07277029,  0.09321148, -0.18006046,  0.00208538, -0.03167614,
         0.09388597, -0.02224447, -0.04625251,  0.13512263,  0.04195321,
        -0.21242853, -0.02117322,  0.01227489,  0.24349554,  0.08646913,
         0.06148387,  0.04573892, -0.12429569,  0.08754396, -0.13705675,
         0.08111668,  0.12703355,  0.12055746,  0.09022795,  0.02763367,
        -0.12121206,  0.0367313 ,  0.10383959, -0.07979403,  0.04381775,
         0.03171287,  0.00111054, -0.00232351, -0.12633115,  0.23080139,
         0.09750164, -0.11096758, -0.16802217,  0.1